# permissions to do viewer timatrixes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: timatrix-viewer-role
rules:
- apiGroups:
  - product.alauda.io
  resources:
  - timatrixes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - product.alauda.io
  resources:
  - timatrixes/status
  verbs:
  - get
